language: erlang
otp_release:
  - 18.3

os:
  - linux
  - osx

env:
  - ELIXIR_VERSION=1.2.4

before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
  - unzip -d elixir Precompiled.zip

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - cd blinky
  - mix deps.get
  - mix firmware --verbosity=verbose
