language: erlang
otp_release:
  - 18.3

sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - ELIXIR_VERSION=1.2.4
  matrix:
    - NERVES_TARGET=rpi
    - NERVES_TARGET=rpi2
    - NERVES_TARGET=rpi3
    - NERVES_TARGET=bbb
    - NERVES_TARGET=alix
    - NERVES_TARGET=ev3

before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
  - unzip -d elixir Precompiled.zip
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://github.com/fhunleth/fwup/releases/download/v0.6.1/fwup_0.6.1_amd64.deb
      sudo dpkg -i fwup_0.6.1_amd64.deb
    else
      brew update;
      brew install fwup;
      brew install squashfs;
      brew install coreutils;
    fi

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - cd blinky
  - mix deps.get
  - mix firmware --verbosity=verbose
