language: elixir
elixir:
  - 1.2.4
otp_release:
  - 18.3

script:
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - cd blinky
  - mix deps.get
  - mix firmware --verbosity=verbose
